In [1]:
import numpy as np

In [6]:
X = np.random.uniform(size=(5,3))
X

array([[0.83406387, 0.67184443, 0.66369834],
       [0.51427879, 0.34995784, 0.18676119],
       [0.44791852, 0.04967944, 0.06675561],
       [0.93733188, 0.40386344, 0.08716619],
       [0.08385109, 0.60988643, 0.58194698]])

In [9]:
W = np.random.uniform(size=(3,4))
W

array([[0.37215746, 0.86433655, 0.27302384, 0.19998957],
       [0.78845456, 0.16238793, 0.26350195, 0.30514161],
       [0.28068873, 0.18839596, 0.99186056, 0.83214696]])

In [10]:
X@W

array([[1.02641454, 0.9550494 , 1.06304785, 0.92410632],
       [0.5197403 , 0.53652394, 0.417866  , 0.36504985],
       [0.22460375, 0.40779618, 0.20159532, 0.16028877],
       [0.69172959, 0.89217451, 0.44878947, 0.38322722],
       [0.6754195 , 0.28115022, 0.76080986, 0.68713648]])

In [12]:
(0.25*X) @ (4*W)

array([[1.02641454, 0.9550494 , 1.06304785, 0.92410632],
       [0.5197403 , 0.53652394, 0.417866  , 0.36504985],
       [0.22460375, 0.40779618, 0.20159532, 0.16028877],
       [0.69172959, 0.89217451, 0.44878947, 0.38322722],
       [0.6754195 , 0.28115022, 0.76080986, 0.68713648]])