In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
T = 1.
F = -1.

In [3]:
inputs = np.array([[T, T ,1], # X1, X2, b
                  [T, F ,1],
                  [F, T ,1],
                  [F, F ,1]])
print(inputs)
print(inputs.shape)

[[ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [-1. -1.  1.]]
(4, 3)


In [4]:
outputs = np.array([[T],
                   [F],
                   [F],
                   [F]])
print(outputs)
print(outputs.shape)

[[ 1.]
 [-1.]
 [-1.]
 [-1.]]
(4, 1)


In [5]:
Y = outputs
X = inputs

In [6]:
W = np.array([[0.2], [0.3], [0.1]])
W

array([[0.2],
       [0.3],
       [0.1]])

In [13]:
# Test
X[0] * W[:,0]

array([0.2, 0.3, 0.1])

In [19]:
y = (X[0]*W[:,0]).sum()
Y[0]

array([1.])

In [78]:
alpha = 0.1
for i in range(len(X)):
    y = (X[i]*W[:,0]).sum()
    t = Y[i]
    delta = t - y
    print('y = ', y)
    print('t = ', t)
    print('t-y=', delta)
    for j in range(len(W)):
        print('W',j,' = ', W[j])
        print('X{}{} = '.format(i,j), X[i,j])
        W[j] += alpha * delta * X[i, j]
        print()

y =  0.41176463135388164
t =  [1.]
t-y= [0.58823537]
W 0  =  [0.47058821]
X00 =  1.0

W 1  =  [0.44117641]
X01 =  1.0

W 2  =  [-0.49999999]
X02 =  1.0

y =  -0.4117646501548654
t =  [-1.]
t-y= [-0.58823535]
W 0  =  [0.52941174]
X10 =  1.0

W 1  =  [0.49999995]
X11 =  -1.0

W 2  =  [-0.44117645]
X12 =  1.0

y =  -0.41176471145054017
t =  [-1.]
t-y= [-0.58823529]
W 0  =  [0.47058821]
X20 =  -1.0

W 1  =  [0.55882348]
X21 =  1.0

W 2  =  [-0.49999998]
X22 =  1.0

y =  -1.5882352023770954
t =  [-1.]
t-y= [0.5882352]
W 0  =  [0.52941174]
X30 =  -1.0

W 1  =  [0.49999995]
X31 =  -1.0

W 2  =  [-0.55882351]
X32 =  1.0



In [79]:
X.dot(W)

array([[ 0.41176466],
       [-0.47058821],
       [-0.52941178],
       [-1.41176464]])

In [80]:
W

array([[ 0.47058822],
       [ 0.44117643],
       [-0.49999999]])

In [82]:
#file:///D:/Engineering%20Books/6th%20Semester/AI/Class%20Slides-BJ/Chapter7b_Artificial_Intelligence.pdf
#page 64

In [81]:
# the delta rule can be made:
# W += alpha * (t-y)
# to
# W -= alpha * (y-t)