In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [43]:
T = 1.
F = -1.

In [44]:
inputs = np.array([[T, T ,1], # X1, X2, b
                  [T, F ,1],
                  [F, T ,1],
                  [F, F ,1]])
print(inputs)
print(inputs.shape)

[[ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [-1. -1.  1.]]
(4, 3)


In [45]:
outputs = np.array([[T],
                   [F],
                   [F],
                   [F]])
print(outputs)
print(outputs.shape)

[[ 1.]
 [-1.]
 [-1.]
 [-1.]]
(4, 1)


In [46]:
Y = outputs
X = inputs

In [47]:
W = np.array([[0.2], [0.3], [0.1]])
W

array([[0.2],
       [0.3],
       [0.1]])

In [48]:
# Test
(X[0] * W[:,0]).sum()

0.6

In [49]:
X.dot(W)

array([[ 6.00000000e-01],
       [ 2.77555756e-17],
       [ 2.00000000e-01],
       [-4.00000000e-01]])

In [50]:
y = X.dot(W)
delta = y - Y
delta

array([[-0.4],
       [ 1. ],
       [ 1.2],
       [ 0.6]])

In [51]:
dW = X.T.dot(delta) * 1./delta.shape[0] ## 1./m
dW

array([[-0.3],
       [-0.2],
       [ 0.6]])

In [52]:
alpha = 0.1

In [53]:
W -= alpha * dW
W

array([[0.23],
       [0.32],
       [0.04]])

In [54]:
# the new output after the update
y = X.dot(W)
y

array([[ 0.59],
       [-0.05],
       [ 0.13],
       [-0.51]])

In [101]:
y = X.dot(W)
delta = y - Y
dW = X.T.dot(delta) #* 1./delta.shape[0] ## 1./m
alpha = 0.1
W -= alpha * dW
# the new output after the update
y = X.dot(W)
y

array([[ 0.50000108],
       [-0.49999462],
       [-0.49999247],
       [-1.49998816]])

In [102]:
W

array([[ 0.49999677],
       [ 0.49999785],
       [-0.49999354]])

In [82]:
#file:///D:/Engineering%20Books/6th%20Semester/AI/Class%20Slides-BJ/Chapter7b_Artificial_Intelligence.pdf
#page 64

In [81]:
# the delta rule can be made:
# W += alpha * (t-y)
# to
# W -= alpha * (y-t)

In [116]:
# Trying with OR gate
X = np.array([[T, T ,1], # X1, X2, b
              [T, F ,1],
              [F, T ,1],
              [F, F ,1]])
Y = np.array([[T],
              [T],
              [T],
              [F]])

In [118]:
W = np.zeros([1,3])

In [119]:
yinv = np.linalg.pinv(Y)
yinv

array([[ 0.25,  0.25,  0.25, -0.25]])

In [120]:
W = yinv.dot(X)
W

array([[0.5, 0.5, 0.5]])

In [121]:
Y.dot(W)

array([[ 0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [-0.5, -0.5, -0.5]])

In [122]:
# bias on the reverse side
# Trying with OR gate
X = np.array([[T, T], # X1, X2, b
              [T, F],
              [F, T],
              [F, F]])
Y = np.array([[T ,1],
              [T ,1],
              [T ,1],
              [F ,1]])

In [123]:
W = np.zeros([2,2])

In [124]:
yinv = np.linalg.pinv(Y)
yinv

array([[ 0.16666667,  0.16666667,  0.16666667, -0.5       ],
       [ 0.16666667,  0.16666667,  0.16666667,  0.5       ]])

In [125]:
W = yinv.dot(X)
W

array([[ 0.66666667,  0.66666667],
       [-0.33333333, -0.33333333]])

In [126]:
Y.dot(W)

array([[ 0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333],
       [-1.        , -1.        ]])