In [34]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
T = 1.
F = -1.

In [36]:
inputs = np.array([[T, T ,1], # X1, X2, b
                  [T, F ,1],
                  [F, T ,1],
                  [F, F ,1]])
print(inputs)
print(inputs.shape)

[[ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [-1. -1.  1.]]
(4, 3)


In [37]:
outputs = np.array([[T],
                   [F],
                   [F],
                   [F]])
print(outputs)
print(outputs.shape)

[[ 1.]
 [-1.]
 [-1.]
 [-1.]]
(4, 1)


In [38]:
Y = outputs
X = inputs

In [46]:
W = np.zeros([3,1])
print(W)
print(W.shape)

[[0.]
 [0.]
 [0.]]
(3, 1)


In [58]:
# For initial W = 0, vectorized
# file:///C:/Users/HeyThere/Downloads/Documents/Ch7_pres.pdf   -- page 4
W = Y.T.dot(X).T
W

array([[ 2.],
       [ 2.],
       [-2.]])

In [65]:
X.dot(W)

array([[ 2.],
       [-2.],
       [-2.],
       [-6.]])

In [62]:
# Inverse method  -- page 9
xinv = np.linalg.pinv(X)
print(xinv)
print(xinv.shape)

[[ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25  0.25  0.25  0.25]]
(3, 4)


In [64]:
Wi = xinv.dot(Y)
Wi

array([[ 0.5],
       [ 0.5],
       [-0.5]])

In [66]:
X.dot(Wi)

array([[ 0.5],
       [-0.5],
       [-0.5],
       [-1.5]])

In [69]:
# Trying with OR gate
X = np.array([[T, T ,1], # X1, X2, b
              [T, F ,1],
              [F, T ,1],
              [F, F ,1]])
Y = np.array([[T],
              [T],
              [T],
              [F]])

In [70]:
W = np.zeros([3,1])

In [71]:
xinv = np.linalg.pinv(X)

In [72]:
W = xinv.dot(Y)

In [73]:
X.dot(W) # works great :)

array([[ 1.5],
       [ 0.5],
       [ 0.5],
       [-0.5]])