In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [50]:
T = 1.
F = -1.

In [51]:
inputs = np.array([[T, T ,1], # X1, X2, b
                  [T, F ,1],
                  [F, T ,1],
                  [F, F ,1]])
print(inputs)
print(inputs.shape)

[[ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [-1. -1.  1.]]
(4, 3)


In [52]:
outputs = np.array([[T],
                   [F],
                   [F],
                   [F]])
print(outputs)
print(outputs.shape)

[[ 1.]
 [-1.]
 [-1.]
 [-1.]]
(4, 1)


In [53]:
Y = outputs
X = inputs

In [55]:
W = np.random.randn(3,1)
W
###
# Basic initialization done

array([[-0.8412564 ],
       [-0.72673318],
       [ 0.44622627]])

In [69]:
# trying the traditional method
y = X.dot(W)
delta = y - Y
dW = X.T.dot(delta) #* 1./delta.shape[0] ## 1./m
alpha = 0.1
W -= alpha * dW
# the new output after the update
y = X.dot(W)
y

array([[ 0.49872912],
       [-0.49934824],
       [-0.49916875],
       [-1.49724611]])

In [19]:
# loop begins here
Wi = np.linalg.pinv(W)
Wi

array([[-0.58509804,  0.51475289]])

In [20]:
y = X.dot(W)
print(y)
print(y.shape)

[[-0.11583067]
 [-1.81101986]
 [ 1.81101986]
 [ 0.11583067]]
(4, 1)


In [21]:
x = y.dot(Wi)
x

array([[ 0.0677723 , -0.05962417],
       [ 1.05962417, -0.9322277 ],
       [-1.05962417,  0.9322277 ],
       [-0.0677723 ,  0.05962417]])

In [22]:
delta = Y - y
print(delta)
delta = delta**2
delta.mean()

[[ 1.11583067]
 [ 0.81101986]
 [-2.81101986]
 [-1.11583067]]


2.7624355119108714

In [23]:
defta = X - x
print(defta)
defta = defta**2
defta.mean()

[[ 0.9322277   1.05962417]
 [-0.05962417 -0.0677723 ]
 [ 0.05962417  0.0677723 ]
 [-0.9322277  -1.05962417]]


0.5000000000000001

In [24]:
dW1 = X.T.dot(delta)/delta.shape[0]
dW1

array([[-1.81101986],
       [ 1.81101986]])

In [25]:
W = W - dW1 * 0.1
W

array([[-0.78232328],
       [ 0.66649261]])

In [26]:
# after forward encoding correction:
y = X.dot(W)
delta = Y - y
print(delta)
delta = delta**2
delta.mean()

[[ 1.11583067]
 [ 0.44881589]
 [-2.44881589]
 [-1.11583067]]


2.1720727824631583

In [27]:
dWi2 = Y.T.dot(defta)/defta.shape[0]
dWi2

array([[-0.00177752, -0.00229654]])

In [28]:
Wi = Wi - dWi2 * 0.1
Wi

array([[-0.58492029,  0.51498254]])

In [29]:
Wii = np.linalg.pinv(Wi)
Wii

array([[-0.96308737],
       [ 0.84793294]])

In [30]:
# after backward encoding correction:
y = X.dot(Wii)
delta = Y - y
print(delta)
delta = delta**2
delta.mean()

[[ 1.11515443]
 [ 0.81102031]
 [-2.81102031]
 [-1.11515443]]


2.7616819734285745

In [31]:
W = (W + Wii)/2
W

array([[-0.87270532],
       [ 0.75721278]])

In [32]:
delta = Y - X.dot(W)
print(delta)
delta = delta **2
delta.mean()

[[ 1.11549255]
 [ 0.6299181 ]
 [-2.6299181 ]
 [-1.11549255]]


2.4504783157950607

In [33]:
for i in range(0, 100):
    print("Weight = ", W)
    Wi = np.linalg.pinv(W)
    print("Weight I ", Wi)
    
    y = X.dot(W)
    print("X.W = ", y)
    x = y.dot(Wi)
    print("y.Wi = ", x)
    delf = Y - y
    print("delf = ", delf, (delf**2).mean())
    delb = X - x
    print("delb = ", delb, (delb**2).mean())

    dW = X.T.dot(delf)/delf.shape[0]
    dWi = Y.T.dot(delb)/delb.shape[0]
    W = W - dW * 0.01
    Wi = Wi - dWi * 0.01
    print('Wi ' , Wi)

    Wii = np.linalg.pinv(Wi)
    print('Wii ' , Wii)
    W = (W + Wii)/2
    print()
    print("New W = ", W)
    print("new del = ", Y - X.dot(W))

Weight =  [[-0.87270532]
 [ 0.75721278]]
Weight I  [[-0.65371882  0.56720663]]
X.W =  [[-0.11549255]
 [-1.6299181 ]
 [ 1.6299181 ]
 [ 0.11549255]]
y.Wi =  [[ 0.07549965 -0.06550814]
 [ 1.06550814 -0.92450035]
 [-1.06550814  0.92450035]
 [-0.07549965  0.06550814]]
delf =  [[ 1.11549255]
 [ 0.6299181 ]
 [-2.6299181 ]
 [-1.11549255]] 2.4504783157950607
delb =  [[ 0.92450035  1.06550814]
 [-0.06550814 -0.07549965]
 [ 0.06550814  0.07549965]
 [-0.92450035 -1.06550814]] 0.5
Wi  [[-0.65834132  0.56187909]]
Wii  [[-0.87881793]
 [ 0.75005077]]

New W =  [[-0.88262515]
 [ 0.75491784]]
new del =  [[ 1.12770732]
 [ 0.63754299]
 [-2.63754299]
 [-1.12770732]]
Weight =  [[-0.88262515]
 [ 0.75491784]]
Weight I  [[-0.65431594  0.55964275]]
X.W =  [[-0.12770732]
 [-1.63754299]
 [ 1.63754299]
 [ 0.12770732]]
y.Wi =  [[ 0.08356093 -0.07147047]
 [ 1.07147047 -0.91643907]
 [-1.07147047  0.91643907]
 [-0.08356093  0.07147047]]
delf =  [[ 1.12770732]
 [ 0.63754299]
 [-2.63754299]
 [-1.12770732]] 2.47663541686

 [-1.87076396]]
Weight =  [[-1.41748693]
 [ 0.54672297]]
Weight I  [[-0.61411583  0.23686372]]
X.W =  [[-0.87076396]
 [-1.9642099 ]
 [ 1.9642099 ]
 [ 0.87076396]]
y.Wi =  [[ 0.53474993 -0.20625239]
 [ 1.20625239 -0.46525007]
 [-1.20625239  0.46525007]
 [-0.53474993  0.20625239]]
delf =  [[ 1.87076396]
 [ 0.9642099 ]
 [-2.9642099 ]
 [-1.87076396]] 4.178939167637996
delb =  [[ 0.46525007  1.20625239]
 [-0.20625239 -0.53474993]
 [ 0.20625239  0.53474993]
 [-0.46525007 -1.20625239]] 0.49999999999999994
Wi  [[-0.61644208  0.23083246]]
Wii  [[-1.4227191 ]
 [ 0.53275037]]

New W =  [[-1.42969045]
 [ 0.53997029]]
new del =  [[ 1.88972016]
 [ 0.96966074]
 [-2.96966074]
 [-1.88972016]]
Weight =  [[-1.42969045]
 [ 0.53997029]]
Weight I  [[-0.61213437  0.23119296]]
X.W =  [[-0.88972016]
 [-1.96966074]
 [ 1.96966074]
 [ 0.88972016]]
y.Wi =  [[ 0.5446283  -0.20569704]
 [ 1.20569704 -0.4553717 ]
 [-1.20569704  0.4553717 ]
 [-0.5446283   0.20569704]]
delf =  [[ 1.88972016]
 [ 0.96966074]
 [-2.96966074

Wii  [[-1.76003676]
 [ 0.30440196]]

New W =  [[-1.76973855]
 [ 0.31266579]]
new del =  [[ 2.45707276]
 [ 1.08240434]
 [-3.08240434]
 [-2.45707276]]
Weight =  [[-1.76973855]
 [ 0.31266579]]
Weight I  [[-0.54795172  0.09680851]]
X.W =  [[-1.45707276]
 [-2.08240434]
 [ 2.08240434]
 [ 1.45707276]]
y.Wi =  [[ 0.79840553 -0.14105705]
 [ 1.14105705 -0.20159447]
 [-1.14105705  0.20159447]
 [-0.79840553  0.14105705]]
delf =  [[ 2.45707276]
 [ 1.08240434]
 [-3.08240434]
 [-2.45707276]] 5.6868071951509105
delb =  [[ 0.20159447  1.14105705]
 [-0.14105705 -0.79840553]
 [ 0.14105705  0.79840553]
 [-0.20159447 -1.14105705]] 0.5
Wi  [[-0.5489597   0.09110323]]
Wii  [[-1.77280184]
 [ 0.29420734]]

New W =  [[-1.78261889]
 [ 0.30249989]]
new del =  [[ 2.480119  ]
 [ 1.08511878]
 [-3.08511878]
 [-2.480119  ]]
Weight =  [[-1.78261889]
 [ 0.30249989]]
Weight I  [[-0.54527074  0.09252922]]
X.W =  [[-1.480119  ]
 [-2.08511878]
 [ 2.08511878]
 [ 1.480119  ]]
y.Wi =  [[ 0.80706558 -0.13695426]
 [ 1.13695426 -

In [40]:
T = 1
F = 0
X = np.array([[T, T],
                  [T, F],
                  [F, T],
                  [F, F]])
Y = np.array([[T],
                   [F],
                   [F],
                   [F]])

In [41]:
W = np.random.randn(2,1)
W

array([[-0.55575334],
       [ 1.04766436]])

In [42]:
for i in range(0, 100):
    print("Weight = ", W)
    
    y = X.dot(W)
    print("X.W = ", y)

    delf = Y - y
    print("delf = ", delf)

    dW = X.T.dot(delf)/delf.shape[0]
    W = W - dW * 0.1
    delf = Y - X.dot(W)
    print("new del = ", delf)
    print(delf.mean())
    print()

Weight =  [[-0.55575334]
 [ 1.04766436]]
X.W =  [[ 0.49191102]
 [-0.55575334]
 [ 1.04766436]
 [ 0.        ]]
delf =  [[ 0.50808898]
 [ 0.55575334]
 [-1.04766436]
 [ 0.        ]]
new del =  [[ 0.52119566]
 [ 0.5823494 ]
 [-1.06115374]
 [ 0.        ]]
0.010597829351085108

Weight =  [[-0.5823494 ]
 [ 1.06115374]]
X.W =  [[ 0.47880434]
 [-0.5823494 ]
 [ 1.06115374]
 [ 0.        ]]
delf =  [[ 0.52119566]
 [ 0.5823494 ]
 [-1.06115374]
 [ 0.        ]]
new del =  [[ 0.53528533]
 [ 0.60993803]
 [-1.07465269]
 [ 0.        ]]
0.017642666552416475

Weight =  [[-0.60993803]
 [ 1.07465269]]
X.W =  [[ 0.46471467]
 [-0.60993803]
 [ 1.07465269]
 [ 0.        ]]
delf =  [[ 0.53528533]
 [ 0.60993803]
 [-1.07465269]
 [ 0.        ]]
new del =  [[ 0.55043173]
 [ 0.63856861]
 [-1.08813688]
 [ 0.        ]]
0.025215866543847665

Weight =  [[-0.63856861]
 [ 1.08813688]]
X.W =  [[ 0.44956827]
 [-0.63856861]
 [ 1.08813688]
 [ 0.        ]]
delf =  [[ 0.55043173]
 [ 0.63856861]
 [-1.08813688]
 [ 0.        ]]
new de

In [ ]:
# Trask

In [45]:
X = np.array([ [0,0],[0,1],[1,0],[1,1] ])
y = np.array([[0,1,1,1]]).T
W = 2*np.random.random((2,1)) - 1
b = np.zeros(1)
for j in range(60000):
    a1 = np.dot(X,W)
    a1_delta = (y - a1)
    w1_delta = a1.T.dot(a1_delta) / a1_delta.shape[0]
    W = W - w1_delta * 0.1

In [46]:
X.dot(W)

array([[ 0.        ],
       [-0.03024695],
       [ 0.03119128],
       [ 0.00094433]])