In [15]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
X = np.random.uniform(-1,1, size=(4,5))
X

array([[-0.79013965,  0.60131466, -0.12347002,  0.82708671,  0.03126058],
       [-0.54180611,  0.05252372, -0.31632757,  0.76464639,  0.90505527],
       [ 0.48879739,  0.40548716, -0.31966373,  0.52811849, -0.58586846],
       [-0.09086377, -0.49303337, -0.08085707, -0.8357242 , -0.81763495]])

In [30]:
# W = np.random.normal(size=(5,3))
W = np.random.uniform(-1,1, size=(5,3))
W

array([[ 0.22194111, -0.86871251,  0.46676849],
       [-0.67016222, -0.75309537, -0.23428997],
       [-0.33799055, -0.10558079,  0.32666252],
       [-0.91071327, -0.5858674 , -0.72126639],
       [ 0.57946891,  0.95939431,  0.8097936 ]])

In [31]:
np.matmul(X, W)

array([[-1.27173544, -0.20797894, -1.12126254],
       [-0.22045496,  0.88483997, -0.18714194],
       [-0.87567169, -1.56773083, -0.82661516],
       [ 0.62488594,  0.16396183, -0.01264831]])

In [32]:
Y = X.dot(W) # same as matmul
Y

array([[-1.27173544, -0.20797894, -1.12126254],
       [-0.22045496,  0.88483997, -0.18714194],
       [-0.87567169, -1.56773083, -0.82661516],
       [ 0.62488594,  0.16396183, -0.01264831]])

In [33]:
Wi = np.linalg.pinv(W)
Wi

array([[ 0.42557217, -0.54177406, -0.99263928, -0.52690298, -0.47092898],
       [-0.70535755, -0.1227556 ,  0.17803823,  0.09868762,  0.38713558],
       [ 0.37530859,  0.3677855 ,  0.91737894, -0.09073687,  0.67408221]])

In [34]:
print(W.dot(Wi))
print(Wi.dot(W))

[[ 0.88238711  0.15806807  0.05323208 -0.24502571 -0.12618768]
 [ 0.15806807  0.36935473  0.31621689  0.30004802 -0.13388191]
 [ 0.05323208  0.31621689  0.6163786   0.13802838  0.33849286]
 [-0.24502571  0.30004802  0.13802838  0.48748513 -0.28412169]
 [-0.12618768 -0.13388191  0.33849286 -0.28412169  0.64439444]]
[[ 1.00000000e+00 -1.86296207e-16 -5.42616285e-17]
 [-2.19756618e-17  1.00000000e+00 -5.08297762e-17]
 [-3.55423715e-16  3.00671586e-16  1.00000000e+00]]


In [35]:
print("X=",X)
print(X.shape,"\n")
print("W=",W)
print(W.shape,"\n")
print("Y=",Y)
print(Y.shape,"\n")

print("Wi=",Wi)
print(Wi.shape,"\n")

X= [[-0.79013965  0.60131466 -0.12347002  0.82708671  0.03126058]
 [-0.54180611  0.05252372 -0.31632757  0.76464639  0.90505527]
 [ 0.48879739  0.40548716 -0.31966373  0.52811849 -0.58586846]
 [-0.09086377 -0.49303337 -0.08085707 -0.8357242  -0.81763495]]
(4, 5) 

W= [[ 0.22194111 -0.86871251  0.46676849]
 [-0.67016222 -0.75309537 -0.23428997]
 [-0.33799055 -0.10558079  0.32666252]
 [-0.91071327 -0.5858674  -0.72126639]
 [ 0.57946891  0.95939431  0.8097936 ]]
(5, 3) 

Y= [[-1.27173544 -0.20797894 -1.12126254]
 [-0.22045496  0.88483997 -0.18714194]
 [-0.87567169 -1.56773083 -0.82661516]
 [ 0.62488594  0.16396183 -0.01264831]]
(4, 3) 

Wi= [[ 0.42557217 -0.54177406 -0.99263928 -0.52690298 -0.47092898]
 [-0.70535755 -0.1227556   0.17803823  0.09868762  0.38713558]
 [ 0.37530859  0.3677855   0.91737894 -0.09073687  0.67408221]]
(3, 5) 



In [36]:
Xi = Y@Wi
Xi

array([[-0.81533517,  0.30213976,  0.19672371,  0.75129609, -0.23744211],
       [-0.78818403, -0.05801038,  0.20468752,  0.2204618 ,  0.32022261],
       [ 0.4229135 ,  0.36284689, -0.16820924,  0.38168287, -0.75175179],
       [ 0.14553533, -0.3633261 , -0.60269815, -0.31192559, -0.23932744]])

In [28]:
Xi - X

array([[ 0.27215987, -0.57363933, -0.46939884, -0.13497349,  0.10050564],
       [ 0.22351644, -0.43188949, -0.68446175,  0.09185301, -0.28313517],
       [ 0.06884945, -0.19025788,  0.2253302 , -0.26743791,  0.44628832],
       [ 0.03725156, -0.155474  ,  0.5223319 , -0.41619204,  0.73124316]])