In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

c:\users\heythere\appdata\local\programs\python\python35\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
from tensorflow.examples.tutorials.mnist import input_data

In [3]:
mnist = input_data.read_data_sets("../../Tensorflow-Bootcamp-master/03-Convolutional-Neural-Networks/MNIST_data/",one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ../../Tensorflow-Bootcamp-master/03-Convolutional-Neural-Networks/MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ../../Tensorflow-Bootcamp-master/03-Convolutional-Neural-Networks/MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting ../../Tensorflow-Bootcamp-master/03-Convolutional-Neural-Networks/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../../Tensorflow-Bootcamp-master/03-Convolutional-Neural-Networks/MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [19]:
tf.reset_default_graph() 

In [33]:
# DEFINE parameters
num_inputs = 784 # 28*28
neurons_hid1 = 392
neurons_hid2 = 196
neurons_hid3 = 98
neurons_hid4 = 49
neurons_hid5 = 25
neurons_hid6 = 12
neurons_hid7 = 6
neurons_hid8 = 3
neurons_hid9 = 2
neurons_hid10 = 1

learning_rate = 0.0003

In [21]:
# PINV(PSEUDO-INVERSE) function
def pinv(a, rcond=1e-15):
    s, u, v = tf.svd(a)
    # Ignore singular values close to zero to prevent numerical overflow
    limit = rcond * tf.reduce_max(s)
    non_zero = tf.greater(s, limit)

    reciprocal = tf.where(non_zero, tf.reciprocal(s), tf.zeros(s.shape))
    lhs = tf.matmul(v, tf.diag(reciprocal))
    return tf.matmul(lhs, u, transpose_b=True)

In [22]:
# TRANSPOSE OR PINV
tie_weight = tf.transpose #pinv

In [23]:
## PLACEHOLDER DEFINATION
X = tf.placeholder(tf.float32, shape=[None, num_inputs])

In [24]:
## WEIGHTS DEFINATION
initializer = tf.variance_scaling_initializer()
w1 = tf.Variable(np.load('./save/weights/w1.npy'))
w2 = tf.Variable(np.load('./save/weights/w2.npy'))
w3 = tf.Variable(np.load('./save/weights/w3.npy'))
w4 = tf.Variable(np.load('./save/weights/w4.npy'))
w5 = tf.Variable(np.load('./save/weights/w5.npy'))
w6 = tf.Variable(np.load('./save/weights/w6.npy'))
w7 = tf.Variable(np.load('./save/weights/w7.npy'))
w8 = tf.Variable(np.load('./save/weights/w8.npy'))
w9 = tf.Variable(np.load('./save/weights/w9.npy'))
w10 = tf.Variable(np.load('./save/weights/w10.npy'))


In [25]:
# ACTIVATION FUNCTION  [ lambda X:X  <OR>  tf.nn.relu  ]
act_func = lambda X:X #tf.nn.relu

In [26]:
# LAYER MODELING OF :NN
hid_layer1 = act_func(tf.matmul(X, w1))
hid_layer2 = act_func(tf.matmul(hid_layer1, w2))
hid_layer3 = act_func(tf.matmul(hid_layer2, w3))
hid_layer4 = act_func(tf.matmul(hid_layer3, w4))
hid_layer5 = act_func(tf.matmul(hid_layer4, w5))
hid_layer6 = act_func(tf.matmul(hid_layer5, w6))
hid_layer7 = act_func(tf.matmul(hid_layer6, w7))
hid_layer8 = act_func(tf.matmul(hid_layer7, w8))
hid_layer9 = act_func(tf.matmul(hid_layer8, w9))

hid_layer10 = act_func(tf.matmul(hid_layer9, w10))

# Layer 10

In [27]:
XX = tf.placeholder(tf.float32, shape=[None, neurons_hid9])
YY = tf.placeholder(tf.float32, shape=[None, neurons_hid10])

ww10 = tf.Variable(initializer([neurons_hid9, neurons_hid10]), dtype=tf.float32)
yy = tf.matmul(XX,ww10)


In [34]:
# LOSS FUNCTIONS
optimizer = tf.train.AdamOptimizer(learning_rate)
loss = tf.reduce_mean(tf.square(yy - YY))
# loss = tf.reduce_mean(tf.abs(output_layer - X))
# cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y,logits=yout))

In [35]:
# TRAINING
train = optimizer.minimize(loss, var_list=[ww10])

In [36]:
# PREPARATION
init = tf.global_variables_initializer()
saver = tf.train.Saver() 

In [37]:
num_epochs = 100
batch_size = 150

try:
    with tf.Session() as sess:
        sess.run(init)

        # Epoch == Entire Training Set
        for epoch in range(num_epochs):
            num_batches = mnist.train.num_examples // batch_size

            # 150 batch size
            for iteration in range(num_batches):
                X_batch, y_batch = mnist.train.next_batch(batch_size)
                ip, op = sess.run([hid_layer9, hid_layer10], feed_dict={X: X_batch})
                
                sess.run(train, feed_dict={XX:ip, YY:op})

            training_loss = loss.eval(feed_dict={XX:ip, YY:op})   
            print("Epoch {} Complete. Training Loss: {}".format(epoch,training_loss))
            saver.save(sess, "./save/aeRev_10_1.ckpt")      
except KeyboardInterrupt:
    print('Keyboard Interrupted')
finally:
    print('Finished Training the Model')

Epoch 0 Complete. Training Loss: 122.4677963256836
Epoch 1 Complete. Training Loss: 104.9327392578125
Epoch 2 Complete. Training Loss: 87.79065704345703
Epoch 3 Complete. Training Loss: 73.78736114501953
Epoch 4 Complete. Training Loss: 57.59215545654297
Epoch 5 Complete. Training Loss: 47.2044792175293
Epoch 6 Complete. Training Loss: 38.66794967651367
Epoch 7 Complete. Training Loss: 28.8687801361084
Epoch 8 Complete. Training Loss: 20.530502319335938
Epoch 9 Complete. Training Loss: 15.582742691040039
Epoch 10 Complete. Training Loss: 11.892380714416504
Epoch 11 Complete. Training Loss: 9.250951766967773
Epoch 12 Complete. Training Loss: 6.019069194793701
Epoch 13 Complete. Training Loss: 3.805098056793213
Epoch 14 Complete. Training Loss: 2.5428600311279297
Epoch 15 Complete. Training Loss: 1.7146263122558594
Epoch 16 Complete. Training Loss: 1.256859302520752
Epoch 17 Complete. Training Loss: 1.1368473768234253
Epoch 18 Complete. Training Loss: 0.77633136510849
Epoch 19 Complete. 

In [41]:
num_test_images = 10
start_point = 15
with tf.Session() as sess:
    
    saver.restore(sess,"./save/aeRev_10_1.ckpt")
    weight10 = w10.eval()
    weigh_10 = ww10.eval()

INFO:tensorflow:Restoring parameters from ./save/aeRev_10_1.ckpt


In [47]:
print('Actual')
print(weight10)
print('\nComputed')
print(weigh_10)
print('\nDifference')
print(weight10-weigh_10)

Actual
[[-0.47105718]
 [ 1.2374369 ]]

Computed
[[-0.47105303]
 [ 1.2374338 ]]

Difference
[[-4.1425228e-06]
 [ 3.0994415e-06]]


In [33]:
print(weight10)
np.save('./save/weights/w10.npy',weight10)
#wt1 = np.load('./save/weights/w1.npy')

[[-0.47105718]
 [ 1.2374369 ]]
