In [1]:
import numpy as np
import mylibrary.nnlib as tnn
import matplotlib.pyplot as plt
import matplotlib
import copy

## Testing Properties of Matrix

In [348]:
W1 = np.random.uniform(-1,1,size=(4, 5))
W1

array([[-0.64890679,  0.35084263,  0.71197384,  0.00360157,  0.52918177],
       [ 0.13611889,  0.86856092,  0.07884713,  0.55163437,  0.37556427],
       [-0.99890367,  0.32924324, -0.62296168,  0.79051637,  0.12051709],
       [-0.77875821,  0.23050976,  0.53239612,  0.79761836,  0.1624288 ]])

In [349]:
W1 = W1__

In [350]:
## computing the scale and direction of input layer
in_norm = np.linalg.norm(W1, ord=2, axis=1, keepdims=True)
in_norm

array([[1.11803399],
       [1.11803399],
       [1.11803399],
       [1.11803399]])

In [351]:
W1_ = W1/in_norm
W1_

array([[-0.52567148, -0.28652521,  0.27641078, -0.63268757,  0.40604965],
       [ 0.10377203, -0.78291784, -0.2748361 , -0.25350184, -0.48628486],
       [ 0.18982524,  0.11956181, -0.76873495,  0.36615142, -0.47397369],
       [ 0.69055575, -0.30107796, -0.23897442, -0.44874981, -0.41713266]])

In [352]:
np.linalg.norm(W1_, ord=2, axis=1, keepdims=True)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [353]:
W1_@W1_.T

array([[ 1.        ,  0.05673971, -0.77064612, -0.22825229],
       [ 0.05673971,  1.        ,  0.27503376,  0.68966268],
       [-0.77064612,  0.27503376,  1.        ,  0.312195  ],
       [-0.22825229,  0.68966268,  0.312195  ,  1.        ]])

In [355]:
W1_.T@W1_

array([[ 0.8       , -0.11584211, -0.48477202,  0.06589743, -0.64193701],
       [-0.11584211,  0.8       ,  0.11601402,  0.55863846,  0.33329793],
       [-0.48477202,  0.11601402,  0.8       , -0.27944388,  0.70992931],
       [ 0.06589743,  0.55863846, -0.27944388,  0.8       , -0.1199864 ],
       [-0.64193701,  0.33329793,  0.70992931, -0.1199864 ,  0.8       ]])

In [356]:
## computing the scale and direction of output layer
out_norm = np.linalg.norm(W1_, ord=2, axis=0, keepdims=True)
out_norm

array([[0.89442719, 0.89442719, 0.89442719, 0.89442719, 0.89442719]])

In [357]:
W1__ = W1_/out_norm
W1__

array([[-0.58771858, -0.32034492,  0.30903664, -0.70736621,  0.45397731],
       [ 0.11602066, -0.87532875, -0.3072761 , -0.28342367, -0.543683  ],
       [ 0.21223107,  0.13367417, -0.85947181,  0.40936974, -0.52991869],
       [ 0.7720648 , -0.3366154 , -0.26718152, -0.50171754, -0.46636849]])

In [358]:
np.linalg.norm(W1__, ord=2, axis=0, keepdims=True)

array([[1., 1., 1., 1., 1.]])

In [359]:
np.linalg.norm(W1__, ord=2, axis=1, keepdims=True)

array([[1.11803399],
       [1.11803399],
       [1.11803399],
       [1.11803399]])

In [360]:
W1__@W1__.T

array([[ 1.25      ,  0.07092463, -0.96330765, -0.28531536],
       [ 0.07092463,  1.25      ,  0.3437922 ,  0.86207834],
       [-0.96330765,  0.3437922 ,  1.25      ,  0.39024375],
       [-0.28531536,  0.86207834,  0.39024375,  1.25      ]])

In [361]:
W1__.T@W1__

array([[ 1.        , -0.14480264, -0.60596502,  0.08237179, -0.80242127],
       [-0.14480264,  1.        ,  0.14501752,  0.69829807,  0.41662241],
       [-0.60596502,  0.14501752,  1.        , -0.34930485,  0.88741164],
       [ 0.08237179,  0.69829807, -0.34930485,  1.        , -0.149983  ],
       [-0.80242127,  0.41662241,  0.88741164, -0.149983  ,  1.        ]])

In [187]:
error = ((W1__@W1__.T - np.eye(4))**2).mean()
error

0.18975394879059668

### Doing this in cycle

In [286]:
W1__ = np.random.uniform(-1,1,size=(4, 5))
W1__

array([[-0.59840072, -0.49274165,  0.23386572, -0.66742749,  0.49934317],
       [ 0.074215  , -0.84587528, -0.14608953, -0.16800787, -0.3757028 ],
       [ 0.30826412,  0.29331903, -0.9278538 ,  0.55101933, -0.83150626],
       [ 0.68345477, -0.45016191, -0.17579089, -0.41157824, -0.44599245]])

In [334]:
## computing the scale and direction of input layer
W1 = W1__
in_norm = np.linalg.norm(W1, ord=2, axis=1, keepdims=True)
W1_ = W1/in_norm
out_norm = np.linalg.norm(W1_, ord=2, axis=0, keepdims=True)
W1__ = W1_/out_norm
error = ((W1__@W1__.T - np.eye(4))**2).mean()
print(error)

0.26913238985953125


In [246]:
W1__@W1__.T

array([[ 1.25      ,  0.25219834, -0.08638933, -0.6021481 ],
       [ 0.25219834,  1.25      , -0.30613072, -0.55566266],
       [-0.08638933, -0.30613072,  1.25      ,  0.28430473],
       [-0.6021481 , -0.55566266,  0.28430473,  1.25      ]])

In [338]:
W1__.T@W1__

array([[ 1.        , -0.14480264, -0.60596502,  0.08237179, -0.80242127],
       [-0.14480264,  1.        ,  0.14501752,  0.69829807,  0.41662241],
       [-0.60596502,  0.14501752,  1.        , -0.34930485,  0.88741164],
       [ 0.08237179,  0.69829807, -0.34930485,  1.        , -0.149983  ],
       [-0.80242127,  0.41662241,  0.88741164, -0.149983  ,  1.        ]])

## Decomposing Matrix with constraints with GradientDescent

In [343]:
optim = tnn.Adam(0.01)

sa = tnn.Multiplier(4, optimizer=optim)
wa = tnn.WeightsLayer(4, 5, weights=copy.deepcopy(W1), optimizer=optim)
wb = tnn.WeightsLayer(5, 4, weights=copy.deepcopy(W1.T), optimizer=optim)
sb = tnn.Multiplier(5, optimizer=optim)

I4 = np.eye(4)

In [344]:
# sa.multiplier.T * wa.weights * sb.multiplier

In [345]:
# wa.weights@wb.weights

In [347]:
### Training to construct original matrix and Identity matrix

for i in range(5000):
    ### construt original
    aW = sa.multiplier.T * wa.weights
    aWb = aW * sb.multiplier
    
    del_aWb = aWb - W1
    del_sb = (del_aWb * aW).mean(axis=0, keepdims=True)
    del_aW = del_aWb * sb.multiplier
    del_sa = (del_aW * wa.weights).T.mean(axis=0, keepdims=True)
    del_W = (del_aW * sa.multiplier.T)
    
    sa.del_multiplier = del_sa
    wa.del_weights = del_W
    sb.del_multiplier = del_sb
    
    sa.update()
#     wa.update()
    sb.update()
    
    ## make the weights orthogonal
    wb.weights = wa.weights.T
    
    wout = wb.forward(wa.weights)
    dw = wout - I4
    dwa = wb.backward(dw/dw.shape[1]) 
    wa.del_weights += dwa
    
    wa.update()
    wb.update()
    
    if i%1000 == 0:
        print("error = ", (del_aWb**2).mean(), (dw**2).mean())

error =  0.0 0.26913238985953136
error =  0.005710406292605681 0.04240593015212182
error =  0.0057337284772853185 0.04218731851083797
error =  0.005784621510192084 0.04204663368098067
error =  0.005817980369333476 0.04189902862889625


In [160]:
aWb

array([[-0.88823998,  0.53799509,  0.52799776,  0.57734151, -0.83443798],
       [-0.42375352, -0.59081607,  0.89239495,  0.98537997, -0.36498316],
       [ 0.08197809, -0.77544794,  0.09811675, -0.61372622,  0.73443058],
       [-0.252114  ,  0.01773399, -0.09799648, -0.9790891 , -0.22730132]])

In [161]:
W1

array([[-0.88364862,  0.53791029,  0.53309528,  0.57871753, -0.84455432],
       [-0.4282357 , -0.58697509,  0.89582415,  0.99010801, -0.35937232],
       [ 0.10289835, -0.78131519,  0.09321064, -0.6122982 ,  0.72979298],
       [-0.26047194,  0.04196478, -0.09742027, -0.97838514, -0.22416655]])

In [162]:
wa.weights@wa.weights.T

array([[ 0.38542724,  0.24594365, -0.36763487,  0.20507751],
       [ 0.24594365,  0.90721384,  0.12290542, -0.0998257 ],
       [-0.36763487,  0.12290542,  0.81246148,  0.06008837],
       [ 0.20507751, -0.0998257 ,  0.06008837,  0.94178409]])