In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import matplotlib

In [2]:
X = torch.randn(1, 2)
X

tensor([[-0.3486, -1.8345]])

In [3]:
W = torch.randn(2, 3)
W

tensor([[-0.4664,  1.9662,  0.7057],
        [-0.7904, -1.1077, -2.2929]])

In [4]:
Wn = W/torch.norm(W, dim=0, keepdim=True)
Wn.shape

torch.Size([2, 3])

In [5]:
(Wn**2).sum(dim=0)

tensor([1.0000, 1.0000, 1.0000])

In [6]:
Xn = X/torch.norm(X, dim=1, keepdim=True)
Xn

tensor([[-0.1867, -0.9824]])

In [7]:
angles = Xn@Wn
angles

tensor([[0.9410, 0.3195, 0.8840]])

In [8]:
Xn_i = angles@torch.pinverse(Wn)
Xn_i

tensor([[-0.1867, -0.9824]])

In [9]:
## Needs extra angle for inversion

In [10]:
We = torch.randn(2, 1)
We = We/torch.norm(We, dim=0, keepdim=True)
We

tensor([[0.8840],
        [0.4674]])

In [11]:
extra_angle = X@We
extra_angle

tensor([[-1.1657]])

In [12]:
angles, extra_angle

(tensor([[0.9410, 0.3195, 0.8840]]), tensor([[-1.1657]]))

In [13]:
X, Xn, Xn_i

(tensor([[-0.3486, -1.8345]]),
 tensor([[-0.1867, -0.9824]]),
 tensor([[-0.1867, -0.9824]]))

In [14]:
## Reversing magnitude

In [15]:
We_norm = torch.norm(We, dim=0, keepdim=True)
We_norm

tensor([[1.]])

In [16]:
## relative_magnitude = extra_angle
rel_mag = extra_angle
unit_mag = Xn_i@We
rel_mag, unit_mag

(tensor([[-1.1657]]), tensor([[-0.6242]]))

In [17]:
Xn_i/unit_mag*rel_mag

tensor([[-0.3486, -1.8345]])

In [18]:
X

tensor([[-0.3486, -1.8345]])

In [19]:
# Xn_i*extra_angle/We_norm

In [20]:
"""
Here, extra_angle is actually angle*mag (projection), hence is not purely angular.
To make angular, everything should be encoded in angles...
"""
print()

In [21]:
We = torch.randn(2, 1)
We_norm = torch.norm(We, dim=0, keepdim=True)

In [22]:
XWe_vec = We - X.t()
XWe_norm = torch.norm(XWe_vec, dim=0, keepdim=True)
XWe_norm
extra_angle2 = We.t()@XWe_vec/XWe_norm/We_norm ## alpha (cosine form)
extra_angle2 = torch.acos(extra_angle2) ## alpha (radian form)
extra_angle2

tensor([[2.8765]])

In [23]:
## for inverting
## calculating angles
ang_X_O_We = torch.acos(Xn_i@We/We_norm) ## theta
ang_X_O_We

tensor([[0.1579]])

In [24]:
ang_O_X_We = np.pi - ang_X_O_We - extra_angle2 ## beta
ang_O_X_We 

tensor([[0.1071]])

In [25]:
mag_X = We_norm*torch.sin(extra_angle2)/torch.sin(ang_O_X_We)
mag_X

tensor([[1.8674]])

In [26]:
Xn_i*mag_X

tensor([[-0.3486, -1.8345]])

In [27]:
Xn, Xn_i, X

(tensor([[-0.1867, -0.9824]]),
 tensor([[-0.1867, -0.9824]]),
 tensor([[-0.3486, -1.8345]]))

In [28]:
X_i = Xn_i*mag_X
X_i

tensor([[-0.3486, -1.8345]])

In [29]:
## Here, all of the values of angles and extra_angles are only in terms of angles
## only 1 extra angle with differnt reference point (other than origin O is needed)

## In Higer Dimensions

In [30]:
X = torch.randn(1, 4)
X

tensor([[ 0.0429,  0.3643, -0.7980,  0.0494]])

In [31]:
W = torch.randn(4, 4)
W

tensor([[ 1.2545, -0.4896, -1.1693, -0.6228],
        [-0.5094, -0.1495,  1.1459, -0.7239],
        [ 1.1736, -0.1632,  0.6439, -1.0928],
        [ 0.5362, -0.2028, -0.5010, -0.5992]])

In [32]:
Wn = W/torch.norm(W, dim=0, keepdim=True)
Wn.shape

torch.Size([4, 4])

In [33]:
(Wn**2).sum(dim=0)

tensor([1.0000, 1.0000, 1.0000, 1.0000])

In [34]:
Xn = X/torch.norm(X, dim=1, keepdim=True)
Xn

tensor([[ 0.0487,  0.4141, -0.9072,  0.0561]])

In [35]:
angles = Xn@Wn
angles

tensor([[-0.6333,  0.0886, -0.1065,  0.3998]])

In [36]:
Xn_i = angles@torch.pinverse(Wn)
Xn_i

tensor([[ 0.0487,  0.4141, -0.9072,  0.0561]])

In [37]:
## Needs extra angle for inversion

In [38]:
We = torch.randn(4, 1)
We = We/torch.norm(We, dim=0, keepdim=True)

We_norm = torch.norm(We, dim=0, keepdim=True)
We_norm

tensor([[1.]])

In [39]:
XWe_vec = We - X.t()
XWe_norm = torch.norm(XWe_vec, dim=0, keepdim=True)
XWe_norm

tensor([[0.7266]])

In [40]:
extra_angle2 = We.t()@XWe_vec/XWe_norm/We_norm ## alpha (cosine form)
extra_angle2

tensor([[0.5189]])

In [41]:
extra_angle2 = torch.acos(extra_angle2) ## alpha (radian form)

In [42]:
## for inverting
## calculating angles
ang_X_O_We = torch.acos(Xn_i@We/We_norm) ## theta
ang_X_O_We

tensor([[0.7839]])

In [43]:
ang_O_X_We = np.pi - ang_X_O_We - extra_angle2 ## beta
ang_O_X_We 

tensor([[1.3325]])

In [44]:
mag_X = We_norm*torch.sin(extra_angle2)/torch.sin(ang_O_X_We)
mag_X

tensor([[0.8797]])

In [45]:
Xn_i*mag_X

tensor([[ 0.0429,  0.3643, -0.7980,  0.0494]])

In [46]:
Xn, Xn_i, X

(tensor([[ 0.0487,  0.4141, -0.9072,  0.0561]]),
 tensor([[ 0.0487,  0.4141, -0.9072,  0.0561]]),
 tensor([[ 0.0429,  0.3643, -0.7980,  0.0494]]))

In [47]:
X_i = Xn_i*mag_X
X_i

tensor([[ 0.0429,  0.3643, -0.7980,  0.0494]])